# Generated by Django 4.2.1 on 2023-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('codehive_id', models.CharField(max_length=4)),
                ('class_name', models.CharField(choices=[('LISALAB', 'LISALAB'), ('LOVELACE', 'LOVELACE'), ('ANITAB', 'ANITAB')], default='ANITAB', max_length=10)),
                ('class_unit', models.CharField(max_length=20)),
                ('scores', models.PositiveIntegerField()),
                ('total_scores', models.PositiveIntegerField()),
                ('assessment_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('created_at', 'codehive_id')},
            },
        ),
    ]
